### ISSUE TITLE
Borked Sheet Metal Doors

### ISSUE THREAD

**Issue by Bobisnotap** [BlueDuckYT/DustrialDecor#2]
![image](https://user-images.githubusercontent.com/60948714/92542924-5ac87180-f207-11ea-9f8a-bc1608ccd2ff.png)
At certain angles of placement, the top part of Sheet Metal Doors has it's texture flipped the wrong way.

**Comment by BlueDuckYT** [comment]
I'm aware of this issue.  I have no idea what's causing it.  I've done exactly what I did for all the other doors for these, but only these are broken.  I am gonna try to fix it.
