### ISSUE TITLE
Recipe conflicts with Quark

### ISSUE THREAD

**Issue by Brun333rp** [BlueDuckYT/DustrialDecor#6]
Several rusty iron recipes conflict with Quark's iron plate recipes, including the rusty ones. Also, it's kinda weird having to use a water bucket to craft a rusty iron plate with ingots that are already rusty, don't you think?

**Comment by BlueDuckYT** [comment]
I've removed the rusty iron ingots and nuggets from their respective tags, this should no longer be an issue
