### ISSUE TITLE
wrapped ice chains conflict with vanilla iron nuggets to iron ingot recipe

### ISSUE THREAD

**Issue by Quezler** [BlueDuckYT/DustrialDecor#8]
https://github.com/BlueDuckYT/DustrialDecor/blob/02e606441b63af86e1587ebc60233fa1239f6533/src/main/resources/data/dustrial_decor/recipes/wrapped_ice_chains.json#L21

**Comment by NielsPilgaard** [comment]
This was fixed in https://www.curseforge.com/minecraft/mc-mods/dustrial-decor/files/3431548
