### ISSUE TITLE
Redstone Lanterns don't drop when broken.

### ISSUE THREAD

**Issue by Moofellow** [BlueDuckYT/DustrialDecor#9]
Breaking the lantern with all tools has yielded the same result, contrary to other lanterns.

As well as this, the redstone lantern is unaffected by redstone currents, opposite the behavior of its Large variant, which is toggled by redstone.

**Comment by BlueDuckYT** [comment]
I will fix the drop issue.  The small lantern will likely remain unaffected by redstone and be more similar to a redstone torch, or have the ability to be right-clicked on and off.
